// Role definitions and access matrix for the school management system

export const ROLES = {
  STUDENT_PARENT: 'student_parent',
  SUBJECT_TEACHER: 'subject_teacher',
  CLASS_TEACHER: 'class_teacher',
  NON_TEACHING: 'non_teaching',
  ACCOUNTANT: 'accountant',
  PRINCIPAL: 'principal',
  ADMIN: 'admin',
  SUPER_ADMIN: 'super_admin'
};

// Module definitions
export const MODULES = {
  DASHBOARD: 'dashboard',
  TIMETABLE: 'timetable',
  HOMEWORK: 'homework',
  RESULT: 'result',
  REPORTS: 'reports',
  FEES: 'fees',
  PAYROLL: 'payroll',
  ATTENDANCE: 'attendance'
};

// Access levels
export const ACCESS_LEVELS = {
  READ: 'read',
  WRITE: 'write',
  ADMIN: 'admin'
};

// Role-based access control matrix
export const ROLE_PERMISSIONS = {
  [ROLES.STUDENT_PARENT]: {
    [MODULES.DASHBOARD]: [ACCESS_LEVELS.READ], // Notices, Attendance graph, Result, Pending Fees, Current date Timetable
    [MODULES.TIMETABLE]: [ACCESS_LEVELS.READ],
    [MODULES.HOMEWORK]: [ACCESS_LEVELS.READ],
    [MODULES.RESULT]: [ACCESS_LEVELS.READ],
    [MODULES.REPORTS]: [ACCESS_LEVELS.READ] // Fees, Attendance only
  },

  [ROLES.SUBJECT_TEACHER]: {
    [MODULES.DASHBOARD]: [ACCESS_LEVELS.READ], // Notices, Holidays, Attendance (own)
    [MODULES.TIMETABLE]: [ACCESS_LEVELS.READ],
    [MODULES.HOMEWORK]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE],
    [MODULES.RESULT]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE],
    [MODULES.REPORTS]: [ACCESS_LEVELS.READ]
  },

  [ROLES.CLASS_TEACHER]: {
    [MODULES.DASHBOARD]: [ACCESS_LEVELS.READ], // Notices, Holidays, Attendance
    [MODULES.ATTENDANCE]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE],
    [MODULES.TIMETABLE]: [ACCESS_LEVELS.READ],
    [MODULES.HOMEWORK]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE],
    [MODULES.RESULT]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE],
    [MODULES.REPORTS]: [ACCESS_LEVELS.READ],
    [MODULES.FEES]: [ACCESS_LEVELS.READ] // Read-only
  },

  [ROLES.NON_TEACHING]: {
    [MODULES.DASHBOARD]: [ACCESS_LEVELS.READ] // Attendance, Notices only
  },

  [ROLES.ACCOUNTANT]: {
    [MODULES.FEES]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.PAYROLL]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.ATTENDANCE]: [ACCESS_LEVELS.READ] // Teachers attendance only
  },

  [ROLES.PRINCIPAL]: {
    [MODULES.DASHBOARD]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.TIMETABLE]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.HOMEWORK]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.RESULT]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.REPORTS]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.FEES]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.PAYROLL]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.ATTENDANCE]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN]
  },

  [ROLES.ADMIN]: {
    [MODULES.DASHBOARD]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.TIMETABLE]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.HOMEWORK]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.RESULT]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.REPORTS]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.FEES]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.PAYROLL]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.ATTENDANCE]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN]
  },

  [ROLES.SUPER_ADMIN]: {
    [MODULES.DASHBOARD]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.TIMETABLE]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.HOMEWORK]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.RESULT]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.REPORTS]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.FEES]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.PAYROLL]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN],
    [MODULES.ATTENDANCE]: [ACCESS_LEVELS.READ, ACCESS_LEVELS.WRITE, ACCESS_LEVELS.ADMIN]
  }
};

// Helper function to check if a role has access to a module
export function hasModuleAccess(userRole: string, module: string, requiredAccessLevel: string = ACCESS_LEVELS.READ) {
  const rolePermissions = ROLE_PERMISSIONS[userRole as keyof typeof ROLE_PERMISSIONS];
  if (!rolePermissions) return false;
  
  const modulePermissions = rolePermissions[module as keyof typeof rolePermissions];
  if (!modulePermissions) return false;
  
  return modulePermissions.includes(requiredAccessLevel);
}

// Helper function to get all accessible modules for a role
export function getAccessibleModules(userRole: string) {
  const rolePermissions = ROLE_PERMISSIONS[userRole as keyof typeof ROLE_PERMISSIONS];
  if (!rolePermissions) return [];
  
  return Object.keys(rolePermissions);
}

// Helper function to check if user role is valid
export function isValidRole(role: string) {
  return Object.values(ROLES).includes(role as any);
}